version: "3.9"

services:
  seaseq-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    container_name: seaseq-cli
    volumes:
      - .:/app
    working_dir: /app
    command: [
      "--spec", "tests/examples/jsonplaceholder/suite.yaml",
      "--env", "tests/examples/jsonplaceholder/env.json",
      "--openapi", "tests/examples/jsonplaceholder/openapi.json",
      "--out", "reports",
      "--parallel", "4",
      "-v"
    ]

  seaseq-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: seaseq-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      TARGET_SITE_URL: "https://mlbam-park.b12sites.com/"
  