version: "3.9"

services:
  seaseq-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    container_name: seaseq-cli
    volumes:
      - ./reports:/app/reports
      - ./tests:/app/tests
    working_dir: /app
    entrypoint: ["seaqa"]
    command: ["--help"]  # Override this when running test suites

  seaseq-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: seaseq-api
    ports:
      - "8000:8000"
    volumes:
      - ./reports:/app/reports
      - .:/app
    working_dir: /app
    environment:
      - FLASK_APP=api.py
      - FLASK_RUN_HOST=0.0.0.0
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - seaseq-cli  # Ensure CLI is built before API starts if needed for any reason    