version: "3.9"

services:
  seaseq-cli:
    build: .
    container_name: seaseq-cli
    command: [
      "seaseq",
      "--spec", "tests/examples/jsonplaceholder/suite.yaml",
      "--env", "tests/examples/jsonplaceholder/env.json",
      "--openapi", "tests/examples/jsonplaceholder/openapi.json",
      "--out", "reports",
      "--parallel", "4",
      "-v"
    ]
    volumes:
      - .:/app
    working_dir: /app

  seaseq-api:
    build: .
    container_name: seaseq-api
    ports:
      - "8000:8000"
    command: [
      "uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"
    ]
    volumes:
      - .:/app
    working_dir: /app
    environment:
      TARGET_SITE_URL: "https://mlbam-park.b12sites.com/"
